views:
  source.toolkit.fluxcd.io/v1beta2/gitrepositories:
    columns:
      - NAMESPACE
      - NAME
      - SUSPEND:.spec.suspend
      - READY

  kustomize.toolkit.fluxcd.io/v1beta2/kustomizations:
    columns:
      - NAMESPACE
      - NAME
      - SUSPEND:.spec.suspend
